### 보드생성
POST http://localhost:8080/boards
Content-Type: application/json
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}

{
  "title": "todo",
  "description": "안녕하세유"
}


### boardId 설정
@boardId = 1
### 덱 생성
POST http://localhost:8080/boards/{{boardId}}/decks
Content-Type: application/json
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}

{
  "title": "todo2",
  "position": 2
}


###카드 생성
@deckId=1
POST http://localhost:8080/decks/{{deckId}}/cards
Content-Type: application/json
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}

{
  "title" : "process",
  "cardStatus": "COMPLETED",
  "position" : 6,
  "description": "fd",
  "emailOfCardManager": "manager2@naver.com",
  "dueAt": "2024-12-01"


}


###카드 전체 조회(덱별 카드조회)
GET http://localhost:8080/decks/{{deckId}}/cards
Content-Type: application/json
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}


###특정 카드 조회
@cardId=3
GET http://localhost:8080/cards/{{cardId}}
Content-Type: application/json
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}


###작업자별 카드 조회
@userId=1
GET http://localhost:8080/decks/{{deckId}}/cards/{{userId}}
Content-Type: application/json
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}

###상태별 카드 조회
GET http://localhost:8080/decks/{{deckId}}/cards/status
Content-Type: application/json
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}

{
   "cardStatus":"COMPLETED"
}


###댓글 생성
POST http://localhost:8080/cards/{{cardId}}/cardDetails/comments
Content-Type: application/json
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}

{
  "description": "comment"
}


###댓글 전체 조회
GET http://localhost:8080/cards/{{cardId}}/cardDetails/comments
Content-Type: application/json
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}



###댓글 수정
@commentId=3
PUT http://localhost:8080/cards/{{cardId}}/cardDetails/comments/{{commentId}}
Content-Type: application/json
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}

{
  "description" : "comment2"
}

###댓글 삭제
DELETE http://localhost:8080/cards/{{cardId}}/cardDetails/comments/{{commentId}}
Content-Type: application/json
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}


###카드 멤버 초대
POST http://localhost:8080/cards/{{cardId}}/cardDetails/invite
Content-Type: application/json
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}

{
  "email": "manager2@naver.com"
}

###카드 멤버 전체 조회
GET http://localhost:8080/cards/{{cardId}}/cardDetails/cardMembers
Content-Type: application/json
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}


###카드 멤버 삭제
@cardMemberId=11
DELETE http://localhost:8080/cards/{{cardId}}/cardDetails/cardMembers/{{cardMemberId}}
Content-Type: application/json
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}

###카드 상세 수정
PATCH http://localhost:8080/cards/{{cardId}}/cardDetails
Content-Type: application/json
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}

{
  "description": "내용3"
}


###카드 상세 조회
GET http://localhost:8080/cards/{{cardId}}/cardDetails
Content-Type: application/json
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}

