### boardId, deckId 설정
@boardId = 2
@deckId = 1

### 덱 생성
POST http://localhost:8080/boards/{{boardId}}/decks
Content-Type: application/json
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}

{
  "title": "1번덱타이틀",
  "position": 1
}


### 덱 전체 조회
GET http://localhost:8080/boards/{{boardId}}/decks
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}


### 덱 죄회
GET http://localhost:8080/boards/{{boardId}}/decks/{{deckId}}
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}


### 덱 수정
PATCH http://localhost:8080/boards/{{boardId}}/decks/{{deckId}}
Content-Type: application/json
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}

{
  "title": "1번덱타이틀 수정"
}


### 덱 삭제
DELETE http://localhost:8080/boards/{{boardId}}/decks/{{deckId}}
Content-Type: application/json
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}

{
  "title": "complete"
}


### 덱 포지션 변경
PATCH http://localhost:8080/boards/{{boardId}}/decks/{{deckId}}/position
Content-Type: application/json
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}

{
  "position": 4
}